### ISSUE TITLE
Not collecting cookies correctly due to pop-up on the website landing page.

### ISSUE THREAD

**Issue by LCkrogh** [timlib/webXray#19]
Hello

I'm currently in the process of scraping a long list of websites around the world for cookies, which I'll be using for my master thesis. I have an issue however, especially regarding websites in the EU, where you're are pretty much guaranteed to have a pop-up as soon as you load a site, asking you to accept/decline cookie collection (because of the GDPR). The thing is, when this pop-up is open, there's basically no cookie-requests to scrape, as you haven't actually accepted cookie-tracking yet before you enter the website, meaning that there's a minimal amount of data to be collected. Now, if I enable "windowed mode", so that each page will open on my screen for 45 seconds before the scraping is done, I can manually press "accept all cookies" on each website, which then allows for the tool to correctly gather cookie information from the website url. The issue is of course that doing this manually to a couple of thousands of websites every 45 seconds, would require me to sit and press the "accept"-button for many hours (days even) in a row.

So, on to my question. Would there be a way to automate this process? I am not much of a coder myself unfortunately, so I'm having a bit of trouble realizing if this is possible. I know that there are plugins that automatically accept all cookies when you load a website (like this one:  https://chrome.google.com/webstore/detail/i-dont-care-about-cookies/fihnjjcciajhdojfnbdddfaoknhalnja), but would you be able to integrate these in the script? Maybe with Selenium?

I realize that a new version of WebXray should be coming up in 2021 and that this version is not supported anymore, but I hope it is alright that I ask questions regarding it anyway.

Thank you in advance and thank you for allowing me to use your tool in any case.

**Comment by timlib** [comment]
This depends on the definition of "correctly" - this collects cookies set without consent.  Otherwise, you can't use extensions with Chrome in headless mode, which is unfortunate.  In theory the next version offers some areas to inject Javascript into the page so you could have some heuristics (perhaps already present in an extension) that could perform actions on the page.
