### ISSUE TITLE
Creating a separate standalone repo of third party service mappings

### ISSUE THREAD

**Issue by konklone** [timlib/webXray#2]
Hi -- I'm working on a similar/overlapping project to analyze third party service usage on websites. I'll open a separate issue to talk about more general collaboration opportunities, but for this one I wanted to ask about the possibility of moving this file into a place where we can more easily collaborate:

https://github.com/timlib/webXray/blob/master/webxray/resources/org_domains/org_domains.json

That file has very valuable information, and thank you for collecting it. Of course, this data is always changing, and I'm sure a lot has happened in the 7+ months since it was last updated.

I'd like to be able to import a copy of this file into my own projects, as well as have a clear contribution path to an upstream source that is invested in by others. It would also be great to have an easy place to point others who are interested in contributing to this dataset.

What do you think about creating a separate repository for this data? I don't need commit rights, but I think it would streamline collaboration and integration into other projects.

**Comment by konklone** [comment]
Also, while this wasn't on my mind when I opened the issue, I also noticed that the JSON data for these mappings is currently covered under the GPL as part of the overall project. I'm currently working in a CC0/public domain context, and think that's a better fit for data files anyway. 

(I don't think that facts can actually be covered under copyright/copyleft, so that probably doesn't stop me from incorporating the data into my project as-is or in a transformed form, but it's just another way of streamlining use for a variety of downstream uses.)

**Comment by timlib** [comment]
As with the other issue, this is also a near-term priority.  There is now support for mapping ownership between companies.  So the new system can tell you that doubleclick is a part of google which is a part of alphabet.  I've been busy writing the academic papers that came from this new system and fell behind on pushing the code!

**Comment by vecna** [comment]
Hi, just a note, I've worked on another similar project https://github.com/vecna/invi.sible.link repository, it has been used to create focus-website like https://american.muslims.tracking.exposed or https://italian.tracking.exposed or analyze social media shared link such as https://elezioni.tracking.exposed/sorveglianza

invi.sible.link uses phantomJS (but has to be discontinued), seleniumHQ+privacy badger

**Comment by timlib** [comment]
I’m going to close this issue as we can have an offline discussion about  it and there are already other people involved in migrating the list. 

I found a lot of errors in the disconnect list which is why I haven’t used it. I’ll shoot you an email today about the list. 

I’ve spent today doing documentation ahead of the version two release, so it’s coming soon!

**Comment by timlib** [comment]
This has now been done: https://github.com/timlib/webxray_domain_owner_list
