### ISSUE TITLE
unable to generate output : browser and encoding errors

### ISSUE THREAD

**Issue by meggymuggy** [timlib/webXray#22]
Hi! I'm on Windows 10 and haven't been able to generate any output from webXray, whether I try a single-site scan or a test on a page list. I've already checked that headless is set to True in ChromeDriver.py. 

**When I run a single-site scan**, I get the following error message: 

![image](https://user-images.githubusercontent.com/15620047/121425240-2e7d8500-c940-11eb-8435-6a4759f82751.png)

**When I try a page list**, I get a different error message, and the program seems to stall (I tried a page list containing only 3 sites and waited for ~15 minutes; nothing other than the error message was generated). This is the error:

![image](https://user-images.githubusercontent.com/15620047/121425314-448b4580-c940-11eb-925f-de60ab102319.png)

I'd appreciate any help/direction. Thanks!

**Comment by timlib** [comment]
I don't have a windows machine, can you try the list of files it comes with and see if you get the same error? it could be something odd with the file.  make sure you save the file as utf8.

**Comment by timlib** [comment]
also, it seem the URL you are trying to scan has "http" twice, hence not being able to load it.

**Comment by meggymuggy** [comment]
> I don't have a windows machine, can you try the list of files it comes with and see if you get the same error? it could be something odd with the file. make sure you save the file as utf8.

I've tried it with the included list of files (example_sites.txt) and I get the same error: 

![image](https://user-images.githubusercontent.com/15620047/121903443-4f562980-ccf6-11eb-9cbf-7d1e80fcfdac.png)



> also, it seem the URL you are trying to scan has "http" twice, hence not being able to load it.

Thanks for catching this! I'm now able to scan single sites.

**Comment by timlib** [comment]
hm, my guess is there is something wrong with the file, can you try re-downloading it?  it's hard for me to debug w/out a windows machine handy.  :-/
