### ISSUE TITLE
Does not work on Windows 10

### ISSUE THREAD

**Issue by anon2573** [timlib/webXray#26]
I do not know if you have ever tested this on windows 10, but it fails at different steps.

E.g.: (SQLLiteDriver.py ln. 593)
Does not work:
("UPDATE task_queue SET locked = TRUE where id = ?", (task_id,)) 
Does work:
("UPDATE task_queue SET locked = 'TRUE' where id = ?", (task_id,))

E.g.:(ChromeDriver.py ln.97)
Does not work:
subprocess.Popen(chrome_cmd,shell=True,stdin=None,stdout=devnull,stderr=devnull,close_fds=True)
Does work:
subprocess.Popen(chrome_cmd,shell=True,stdin=None,stdout=devnull,stderr=devnull,close_fds=True)

I am currently trying to get it running and if successful I can provide you with the working version.

**Comment by timlib** [comment]
yeah, windows always seems to behave slightly differently - the TRUE vs. 'TRUE' query in particular is odd.  in general *nix compatibility is the higher priority, so as long as no windows bug-fixes introduce errors on *nix-based platforms I'd love the contribution.  thanks for flagging, and I hope to see a pull request!  :-)

**Comment by anon2573** [comment]
Yes I will upload it as soon as I am done, but it will only be tested on Windows 10, so it might introduce errors on any other platform.

**Comment by anon2573** [comment]
I have created a pull request, just a few small changes, I did not have the opportunity to test it on Linux or macOS, maybe you can accept the changes if you have tested it :)
