### ISSUE TITLE
Related project: third party service scanner using Chrome/Lambda

### ISSUE THREAD

**Issue by konklone** [timlib/webXray#3]
I'm also working on performing analysis of third party services using a headless browser. In my case, I'm using a slightly different toolset: 

* Chrome Headless instead of phantomjs (which has been deprecated in favor of Chrome)
* Production of human/Excel-friendly CSV files in addition to a directory of many JSON files (database-agnostic/pre-database output)
* Use of Lambda containers for parallelization instead of local CPU
* Separation of the orchestration tool from the core analysis

The overall orchestration tool is at https://github.com/18F/domain-scan, though getting headless Chrome to work is part of a WIP branch at https://github.com/18F/domain-scan/tree/headless-chrome. My immediate goal is a shallow-but-wide scan of the homepages of tens/hundreds of thousands of HTTP-accessible hostnames, for all third party hosts that get contacted by user browsers. In the future it seems likely that I'll want to branch it out to encompass multiple URLs per-domain, since service use can definitely be page-specific.

There's a clear overlap with the goals of this project, but the toolset is different enough that I don't think I can reuse webXray as-is. But, I wanted to open this issue in case you wanted to discuss ways we might be able to reuse part or all of each others' work.

**Comment by timlib** [comment]
The code up here is way, way, way behind my branch.  The soon-to-be-released webxray 2 has many of these features, most notably chrome support for both headed and headless environments.  The difficult part with chrome is getting all third-party cookies which requires some tricks as selenium doesn't give a full set of cookies, I was stuck on that for a bit.  webxray 2 also has support for mysql, postgres, and sqlite databases.  Hopefully I'll have it up by the end of the month, if not, definitely by the end of next.

**Comment by vecna** [comment]
hi @timlib, probably there is some overlap with my pipeline. I've a service doing orchestration and different nodes performing the analysis, look at: https://invi.sible.link/stats
