### ISSUE TITLE
Doubt about how to use during a session in a SHOP

### ISSUE THREAD

**Issue by gabrielhribeiro** [timlib/webXray#30]
Hello, 

First of all thanks for this amazing enumerator, I was looking for one script like this for a long time. 
I'm trying to use this script during a shopping session. 

I need to simulate a selection of a product but when I paste the URL I lost the session. Do you have any Idea how can I Proceed with this scenario?  https://secure-website.com/checkout/ do you any issue like this? 

https://dev.to/hardiksondagar/reuse-sessions-using-cookies-in-python-selenium-12ca i sow something like this. 

Your code already this kind of functionality? 

Thanks and Best Regards, 
Gabriel

**Comment by timlib** [comment]
One idea I had was the ability to predefine some forms of interaction, much like you’re suggesting, but I never had time to get around to it. In theory it would not be too hard to inject a script to do it and execute that via Chrome dev tools protocol. If you want to take a crack at it look at the code to inject the Readability.js script, could take a similar approach. 👍🏻

**Comment by timlib** [comment]
This may be a way to inject something you want:

https://github.com/timlib/webXray/blob/18b18b552a336830bbac1b202c7cdf5953c1ba81/webxray/ChromeDriver.py#L815

**Comment by gabrielhribeiro** [comment]
Hello, 

Thank you. I will try that and I let you know if put things to working on. 

Regards, 
Gabriel
