### ISSUE TITLE
UnicodeEncodeError: 'charmap'

### ISSUE THREAD

**Issue by gabrielhribeiro** [timlib/webXray#31]
Hi guys, 

I'm trying to use the: python run_webxray.py and following the step but I got the error: UnicodeEncodeError: 'charmap' codec can't encode characters in position 7-10: character maps to <undefined>

Firstly, I thought it was a library but I look more deeper and I saw this article, Maybe can help: https://stackoverflow.com/questions/27092833/unicodeencodeerror-charmap-codec-cant-encode-characters

Thank you. 
Gabriel
..........................................
LOGS: 

     Would you like to:
                [C] Collect Data
                [A] Analyze Data
                [V] Visualize Data
                [PC] Policy Collect
                [PA] Policy Analyze
                [Q] Quit
        Selection: C
        ===============
        Collecting Data
        ===============
        Would you like to:
                [C] Create a New Database
                [A] Add to an Existing Database
                [Q] Quit
        Selection: C
        ----------------------
        Creating New Database
        ----------------------
        Database name must be alpha numeric, and may contain a "_"; maximum length is 20 characters.
        Enter new database name: globo
        Creating new db with name globo
        --------------------
        Selecting Page List
        --------------------
        Please select from the available files in the "page_lists" directory:
        Page Lists Available:
                [0] example_sites.txt

        Choose a page list by number: 0
        Pages file is "example_sites.txt"
        ------------------
        Beginning webXray
        ------------------
        ---------------------------------
         Adding page scans to task queue
        ---------------------------------
        Fetching list of pages already scanned...
         => 0 pages already scanned
        ---------------------
         Building Page Queue
        ---------------------
                1 | https://www.globo.com/... Adding to queue.
----------------------------------------
        Build task queue finished in 0:00:00.066061
----------------------------------------
        ----------------------------------
        1 addresses will now be webXray'd
                ...you can go take a walk. ;-)
        ----------------------------------
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "C:\Python310\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "C:\Python310\lib\multiprocessing\pool.py", line 48, in mapstar
    return list(map(*args))
  File "C:\Users\Gabriel\Desktop\webXray-master\webxray\Collector.py", line 76, in process_tasks_from_queue
    print('\t[p.%s]\t\U0001f3c3\u200d\u2642\ufe0f Starting process' % process_num)
  File "C:\Python310\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 7-10: character maps to <undefined>
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Gabriel\Desktop\webXray-master\run_webxray.py", line 650, in <module>
    interaction()
  File "C:\Users\Gabriel\Desktop\webXray-master\run_webxray.py", line 215, in interaction
    collect(db_name, pages_file_name)
  File "C:\Users\Gabriel\Desktop\webXray-master\run_webxray.py", line 322, in collect
    collector.run(task='process_tasks_from_queue', pool_size=pool_size)
  File "C:\Users\Gabriel\Desktop\webXray-master\webxray\Collector.py", line 693, in run
    myPool.map(self.process_tasks_from_queue, process_num)
  File "C:\Python310\lib\multiprocessing\pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "C:\Python310\lib\multiprocessing\pool.py", line 771, in get
    raise self._value
UnicodeEncodeError: 'charmap' codec can't encode characters in position 7-10: character maps to <undefined>

**Comment by timlib** [comment]
what happens if you use the original unmodified example site list?  I'm guessing perhaps you copy/pasted into it?

**Comment by timlib** [comment]
closing as no follow-up info.
