### ISSUE TITLE
Private mode

### ISSUE THREAD

**Issue by MevreHTW** [timlib/webXray#34]
Hi,

is there any way to collect data in private mode to compare the results with "normal" mode?

**Comment by timlib** [comment]
It’s actually possible I believe, there is a command line flag. If there’s a need I can take a look as I was hoping to push some big updates soon. Let me know if you’re still interested.

**Comment by MevreHTW** [comment]
thank you for your quick reply. i have changed my research question for a term paper after all. For my personal interest, however, I would find the difference exciting.

**Comment by timlib** [comment]
I haven't done testing, but if you insert this at line 93 of ChromeDriver.py I think it will work
`chrome_cmd += ' --incognito'`

**Comment by timlib** [comment]
closing this, feature has been added/tested - enjoy!
