### ISSUE TITLE
make webXray collects data from non-interactive command line

### ISSUE THREAD

**Issue by vecna** [timlib/webXray#5]
Hi tim,

webXray is working if I follow the interactive steps (creation of a database, association to a database from page_lists) but is not working if I command in a non-interactive way, like the output below. 

It works if the database already exists, but I was hoping to do everything without passing through the interactive interface

```
user@user:~/webXray$ python3 run_webxray.py -c ireland ireland.txt
	------------------------
	 Building List of Pages 
	------------------------
Traceback (most recent call last):
  File "run_webxray.py", line 403, in <module>
    collect(db_name, page_file)
  File "run_webxray.py", line 291, in collect
    collector.run(pool_size)
  File "/home/user/webXray/webxray/Collector.py", line 191, in run
    if sql_driver.page_exists(url):
  File "/home/user/webXray/webxray/SQLiteDriver.py", line 187, in page_exists
    self.db.execute("SELECT COUNT(*) FROM page WHERE start_url_md5 = ?", (self.md5_text(url),))
sqlite3.OperationalError: no such table: page
```

**Comment by timlib** [comment]
There is a major update coming, I'll either handle gracefully with an error message or automatically create the database if not exist.

**Comment by vecna** [comment]
Thanks! when do you foresee the release?

**Comment by timlib** [comment]
To be perfectly honest, committing more of my own time to a project which has exactly one single line of code contributed by anybody other than me is not my highest priority.

https://github.com/timlib/webXray/graphs/contributors

**Comment by vecna** [comment]
no problem, but then, please, instead of telling me "a major update coming" give me a tip on where I can patch it, and you'll have three contributors ;)

**Comment by timlib** [comment]
fair enough, look at run_webxray.py

**Comment by timlib** [comment]
refocused on non-expert users, feature removed.
