### ISSUE TITLE
Tried everything but keep getting this error

### ISSUE THREAD

**Issue by Imcon** [timlib/webXray#9]
root@ubuntu:/home/dhorn/Desktop/webxray# google-chrome --version
Google Chrome 75.0.3770.142 
root@ubuntu:/home/dhorn/Desktop/webxray# chromedriver --version
ChromeDriver 75.0.3770.140 (2d9f97485c7b07dc18a74666574f19176731995c-refs/branch-heads/3770@{#1155})
root@ubuntu:/home/dhorn/Desktop/webxray# 

dhorn@ubuntu:~/Desktop/webxray$ python3 run_webxray.py -s http://cnn.com
   
	             | |                        
	__      _____| |____  ___ __ __ _ _   _ 
	\ \ /\ / / _ \ '_ \ \/ / '__/ _` | | | |
	 \ V  V /  __/ |_) >  <| | | (_| | |_| |
	  \_/\_/ \___|_.__/_/\_\_|  \__,_|\__, |
	                                   __/ |
	                                  |___/ 
                            	   	  [v 2.2]
    
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Single Site Test On: http://cnn.com
	Browser type is chrome
	Browser wait time is 45 seconds
		http://cnn.com                                     **_Browser Error: Unable to launch Chrome instance_**
------------------
Quitting, bye bye!
------------------
dhorn@ubuntu:~/Desktop/webxray$

**Comment by Imcon** [comment]
respond to dan@imconintl.com if you can, thanks!

**Comment by timlib** [comment]
Chrome won't run as root, try a non-root user.

**Comment by Imcon** [comment]
Still not working, would running it as a virtualize OS have something to do with it?

Getting this in the terminal when doing the above: Command: google-chrome opens the browsers from the command line but give an ERROR; command_buffer_proxy_impl.cc(170) ... Shared memory region is not valid

![Screen Shot 2019-07-22 at 1 23 09 PM](https://user-images.githubusercontent.com/39218347/61651438-e12c9780-ac83-11e9-8872-c4cb01647952.png)

**Comment by timlib** [comment]
try setting headless to True

https://github.com/timlib/webXray/blob/master/webxray/ChromeDriver.py#L34
